Increase limits for loading DLS files
EmbeddedSynth/sonivox-fork pull request #10
Opened 2023-05-02 20:08 UTC by M-HT

This PR modifies the example program to allow loading a DLS file (to help demonstrate the problem in issue #9) and increases limits to allow loading the tested DLS files, which resolves the issue.

2023-05-02 20:36 UTC, pedrolcl requested changes

2023-05-02 20:36 UTC, pedrolcl commented on example/sonivoxrender.c
>                          "\t-h\tthis help message\n"\
The help text should also mention the new program option:

```suggestion
                        "\t-h\tthis help message\n"\
                        "\t-d file.dls\tDLS soundfont\n"\
```

2023-05-02 20:36 UTC, pedrolcl commented on example/sonivoxrender.c
>  int readFunction(void *handle, void *buffer, int offset, int size) {
I don't like the duplication of a readFunction() for MIDI files and a dlsReadAt() for DLS files. There should be only one Read() and one Size() function.

2023-05-02 20:36 UTC, pedrolcl commented on example/sonivoxrender.c
> +        EAS_FILE mDLSFile;
There may be several MIDI files in the command line, but only one DLS file.  The problem of putting this DLS file processing here is that the DLS file will be loaded again and again for each MIDI file that is going to be rendered. This problem was already present in the program, because the initialization of the library is performed for each MIDI file processed.

A proper fix is that the calls to `EAS_Init()`, `EAS_SetParameter()`, and  `EAS_LoadDLSCollection()` should be moved outside, and before, of the renderFile() function call.

2023-05-03 08:38 UTC, M-HT commented on example/sonivoxrender.c
>                          "\t-h\tthis help message\n"\
Fix in the new commit.

2023-05-03 08:39 UTC, M-HT commented on example/sonivoxrender.c
>  int readFunction(void *handle, void *buffer, int offset, int size) {
Fix in the new commit.

2023-05-03 08:39 UTC, M-HT commented on example/sonivoxrender.c
> +        EAS_FILE mDLSFile;
Fix in the new commit.

2023-05-03 08:39 UTC, M-HT commented
I made the requested changes in the example file.

2023-05-03 18:25 UTC, pedrolcl approved these changes

2023-05-03 18:26 UTC, merged