The new host wrapper
EmbeddedSynth/sonivox-fork pull request #27
Opened 2024-10-27 06:31 UTC by rsp4jack

After profiling about DLS loading, I found EAS's HW was so slow about file operations. It was designed for twenty years ago.
So I reimplemented it, using CRT and some OS-specific APIs. The old one is preserved as optional.

It works on Linux and Windows now, *blazing fast* (compared than before).

2024-11-02 15:16 UTC, rsp4jack commented
The CRT file operations are only used when file->readAt is NULL.

2024-11-02 17:44 UTC, pedrolcl requested changes

2024-11-02 17:44 UTC, pedrolcl commented on CMakeLists.txt
There is another way to determine the endianess of the target architecture using cmake: 
https://cmake.org/cmake/help/latest/module/TestBigEndian.html

First:

```CMake
include(TestBigEndian)
test_big_endian(BIG_ENDIAN)
```

Then:

```CMake
if (BIG_ENDIAN) 
    target_compile_definitions( sonivox-objects PRIVATE BIG_ENDIAN )
    message(STATUS "Big endian byte order detected.")
endif()

if (USE_NEW_HOST_WRAPPER)
    target_compile_definitions( sonivox-objects PRIVATE NEW_HOST_WRAPPER )
endif()
```

2024-11-02 17:44 UTC, pedrolcl commented on arm-wt-22k/src/hostmm_ng.c
> +// --- end
Use the CMake defined macro:

```suggestion
const EAS_BOOL O32_BIG_ENDIAN = 
#ifdef BIG_ENDIAN
    EAS_TRUE;
#else
    EAS_FALSE;
#endif
```

2024-11-02 17:44 UTC, pedrolcl commented on arm-wt-22k/src/hostmm_ng.c
> +    if (msbFirst ^ (O32_HOST_ORDER == O32_BIG_ENDIAN)) {
```suggestion
    if (msbFirst ^ O32_BIG_ENDIAN) {
```

2024-11-02 17:44 UTC, pedrolcl commented on arm-wt-22k/src/hostmm_ng.c
> +    if (msbFirst ^ (O32_HOST_ORDER == O32_BIG_ENDIAN)) {
```suggestion
    if (msbFirst ^O32_BIG_ENDIAN) {
```

2024-11-02 17:44 UTC, pedrolcl commented on example/sonivoxrender.c
> +        // mDLSFile.size = Size;
```suggestion
#ifndef NEW_HOST_WRAPPER
        mDLSFile.readAt = Read;
        mDLSFile.size = Size;
#endif
```

2024-11-02 17:44 UTC, pedrolcl commented on example/sonivoxrender.c
> +    // mEasFile.size = Size;
```suggestion
#ifndef NEW_HOST_WRAPPER
    mEasFile.readAt = Read;
    mEasFile.size = Size;
#endif
    
```

2024-11-03 01:33 UTC, rsp4jack commented on CMakeLists.txt
I think `NEW_HOST_WRAPPER` macro should be defined in eas.h, as it affects the library's behavior.

2024-11-03 02:20 UTC, rsp4jack commented
Benchmark (not authoritative, for information only):

OmegaGMGS2.dls, ~266 MiB, with 484 insts, 15947 regions, 15944 arts and 2255 waves
Old HW:
```
./sonivoxrender -d ~/OmegaGMGS2.dls  23.50s user 22.76s system 99% cpu 46.503 total
```
New HW:
```
./sonivoxrender -d ~/OmegaGMGS2.dls  0.41s user 0.20s system 99% cpu 0.612 total
```

2024-11-03 09:16 UTC, merged

2024-11-03 09:45 UTC, pedrolcl approved these changes

2024-11-07 22:24 UTC, pedrolcl commented
> Benchmark (not authoritative, for information only):
> 
> OmegaGMGS2.dls, ~266 MiB, with 484 insts, 15947 regions, 15944 arts and 2255 waves Old HW:
> 
> ```
> ./sonivoxrender -d ~/OmegaGMGS2.dls  23.50s user 22.76s system 99% cpu 46.503 total
> ```
> 
> New HW:
> 
> ```
> ./sonivoxrender -d ~/OmegaGMGS2.dls  0.41s user 0.20s system 99% cpu 0.612 total
> ```

Where can I find OmegaGMGS2.dls? I can only find the sf2 version of it.

2024-11-09 12:42 UTC, rsp4jack commented
> Where can I find OmegaGMGS2.dls? I can only find the sf2 version of it.

It is converted from the sf2 version, using Extreme Sample Converter.
BTW, the eas_mdls limits are increased to make it load.

2024-11-09 18:49 UTC, pedrolcl commented
> > Where can I find OmegaGMGS2.dls? I can only find the sf2 version of it.
> 
> It is converted from the sf2 version, using Extreme Sample Converter.

I've tested [Airfont 340.dls](http://www.ronimusic.com/sf2/Airfont_340.dls), ~80 MiB [from this page](http://www.ronimusic.com/smp_ios_dls_files.htm) and the benefit is evident. 

Please take a look to my modifications. I want to do more checks before a new release.

2024-11-10 02:13 UTC, rsp4jack commented
> Please take a look to my modifications. I want to do more checks before a new release.

EAS's duplicated handle has its own position indicator, but as I know, dup()-ed file descriptors share the same I/O object (so file position is same).

Use dup() to implement DupHandle will not work on Linux (as I tested it), but according to CI it works on FreeBSD.

2024-11-11 06:22 UTC, pedrolcl commented
> according to CI it works on FreeBSD and MacOS. Confused about how it works

CI is only proving that the code is compiling, and the unit tests are passing. But unit tests are only testing MIDI file processing without DLS files. Other manual tests with the sonivoxrender program show that FreeBSD reads correctly all DLS files, but macOS doesn't. What is needed:
- Unit tests that include DLS. The main problem is having a free and reasonable sized DLS to be included in the repository for testing.
- I am not happy with the special Linux implementation. There should be a single DupHandle implementation for all POSIX platforms.

The alternative right now is to enable at configuration time the new host wrapper for some platforms and the old wrapper for others. This doesn't feel right for a release.

2024-11-17 01:31 UTC, rsp4jack commented
I found that even passing ReadAt to the new HW, it is still much faster than the old one:

```
./sonivoxrender -d ~/OmegaGMGS2.dls  3.19s user 1.80s system 99% cpu 5.022 total
```

> The alternative right now is to enable at configuration time the new host wrapper for some platforms and the old wrapper for others. This doesn't feel right for a release.

For these platforms, fallback to internal ReadAt in the new HW is okay. I will implement it in the next PR.

2024-11-18 05:40 UTC, pedrolcl commented
I've implemented DLS loading unit tests ('devel' branch). The DLS is downloaded by CMake, so it will work not only in the CI, but also on local builds. You may find two lines like this in CMake output:
```
-- DLS file C:\msys64\tmp/soundfont.dls size: 81362584
-- DLS file C:\msys64\tmp/soundfont.dls MD5 hash: 40c0cd4ad29ae411a8fc3d6681002a2b
```
The DLS file is [AirFont_340.dls](http://www.ronimusic.com/smp_ios_dls_files.htm) but may be easily replaced in the future by something else.